// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0htI1kNJQeRMWBHpE82j7918dkEQ2-c',
    appId: '1:734216900788:web:f99757c9e58b357fe2c7e1',
    messagingSenderId: '734216900788',
    projectId: 'sacuit-exchange',
    authDomain: 'sacuit-exchange.firebaseapp.com',
    storageBucket: 'sacuit-exchange.appspot.com',
    measurementId: 'G-DEWTC2KZKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK30OjSN3VGzTaEj7RKIZb2dOHkxFwC4Y',
    appId: '1:734216900788:android:28d968de4b3792bfe2c7e1',
    messagingSenderId: '734216900788',
    projectId: 'sacuit-exchange',
    storageBucket: 'sacuit-exchange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEy4-KdQvjSsR3d4hSupb3vWg5k5FF8c',
    appId: '1:734216900788:ios:19537dbe69288bb2e2c7e1',
    messagingSenderId: '734216900788',
    projectId: 'sacuit-exchange',
    storageBucket: 'sacuit-exchange.appspot.com',
    iosBundleId: 'com.example.sacuitExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEy4-KdQvjSsR3d4hSupb3vWg5k5FF8c',
    appId: '1:734216900788:ios:19537dbe69288bb2e2c7e1',
    messagingSenderId: '734216900788',
    projectId: 'sacuit-exchange',
    storageBucket: 'sacuit-exchange.appspot.com',
    iosBundleId: 'com.example.sacuitExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD0htI1kNJQeRMWBHpE82j7918dkEQ2-c',
    appId: '1:734216900788:web:4f5ccb108ee63756e2c7e1',
    messagingSenderId: '734216900788',
    projectId: 'sacuit-exchange',
    authDomain: 'sacuit-exchange.firebaseapp.com',
    storageBucket: 'sacuit-exchange.appspot.com',
    measurementId: 'G-2VJ72JZKHT',
  );
}
